export const SELECT_MODE = 'SELECT_MODE';
export const SELECT_ENTRY = 'SELECT_ENTRY';
export const SELECT_OUTPUT_PATH = 'SELECT_OUTPUT_PATH';
export const SELECT_OUTPUT_FILENAME = 'SELECT_OUTPUT_FILENAME';
